### ISSUE TITLE
Can't fetch locators using driver.findElements()

### ISSUE THREAD

**Issue by vidyasagarp** [appium/appium-espresso-driver#462]
using Espresso driver not able to fetch locators using findElements, tried for driver.findElementsByClassName and driver.findElementsById, both didn't work.

Below is the exception i'm getting.
[AppiumLogs.pdf](https://github.com/appium/appium-espresso-driver/files/3314415/AppiumLogs.pdf)

org.openqa.selenium.StaleElementReferenceException: io.appium.espressoserver.lib.handlers.exceptions.StaleElementException: The cached element 3a55aa3f-1c68-44d4-8573-212f5df46cb5 no longer exists in the Android View hierarchy. Try to find it using a locator.
	at io.appium.espressoserver.lib.model.Element$Companion.getViewById(Element.kt:111)
	at io.appium.espressoserver.lib.model.Element$Companion.getViewInteractionById(Element.kt:64)
	at io.appium.espressoserver.lib.handlers.Text.handleInternal(Text.kt:28)
	at io.appium.espressoserver.lib.handlers.Text.handleInternal(Text.kt:24)
	at io.appium.espressoserver.lib.handlers.RequestHandler$DefaultImpls.handle(RequestHandler.kt:28)
	at io.appium.espressoserver.lib.handlers.Text.handle(Text.kt:24)
	at io.appium.espressoserver.lib.handlers.Text.handle(Text.kt:24)
	at io.appium.espressoserver.lib.http.Router.route(Router.kt:216)
	at io.appium.espressoserver.lib.http.Server.serve(Server.kt:53)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

**Environment:**
Appium version (or git revision) that exhibits the issue: v1.14.0-beta.1
EspressoDriver version: 1.13.0
Last Appium version that did not exhibit the issue (if applicable): -
Desktop OS/version used to run Appium: Mac OS 10.14.1
Node.js version (unless using Appium.app|exe): v10.13.0
Npm or Yarn package manager: Npm
Mobile platform/version under test: Android 8
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI

**Code To Reproduce Issue**
 List<WebElement> textList = androidDriver.findElementsByClassName("com.vocera.uc.ui.widget.TextView");
        for (WebElement text:textList)
        {
            if(text.getText().equals(textToClick)) {
                text.click();
                break;
            }
        }

**Comment by mykola-mokhnach** [comment]
Did you try to re-locate the element right before interacting with it like it suggested in the exception message?

**Comment by vidyasagarp** [comment]
Yes, i gave 5 seconds sleep before interacting with the element, the element is visible on UI, still i'm getting the above exception. tried with findElementsByClassName and findElementsById.   
i have multiple locators with same resource id, so i'm iterating through all the locators and fetching the text attribute and performing the action on that particular locator

**Comment by vidyasagarp** [comment]
Closing this issue as it got resolved after using latest commit Id from master branch of java client.

**Comment by Proryanator** [comment]
So I'm having the same issue here too. I put a breakpoint right when I try to access that element, then put a literal 'findElementBy(By.id("locator"))' and I still get a stale exception when I try to click it.

In Appium's Desktop inspector I can see the element, and the locator is correct, even from in there when I click the element and click 'Tap' it throws the same stale exception.

I'm talking to my developer about it, maybe there's something weird he did when he built this page compared to other pages in our app but, it's kinda holding me back.

I tried upgrading the appium-espresso-driver version to 1.42.0, upgrading the espresso-core version from 3.1.0 to 3.3.0 in our android source code, even tried doing a literal 'element.getLocation()' and just clicking there.

There's nothing overtop of these elements that I can tell, so it's kinda odd.

I'm using appium version v1.19.0-rc.0, java8, Appium (so I can't make direct calls to Espresso), any thoughts on the matter? Hopefully there's some changes my dev can make to the flow so that I can interact with it but, worst case scenario I might be SOL :D

**Comment by 0x8BADFOOD** [comment]
I have this issue when I trying to find the element and list contains more than one item.

**Comment by 0x8BADFOOD** [comment]
@Proryanator  make sure that all elements you are using in your list have the "text" field as non-null.

**Comment by Proryanator** [comment]
> @Proryanator  make sure that all elements you are using in your list have the "text" field as non-null.

All the elements as in, in my List<MobileElement> in appium? Or the list in the Android code itself?

**Comment by 0x8BADFOOD** [comment]
In List of appium elements. Where you trying to access them.
