### ISSUE TITLE
Guide on how to build an APK from source code that can be run on appium-espresso-driver

### ISSUE THREAD

**Issue by kulasangeles** [appium/appium-espresso-driver#646]
This is not an issue per se on the driver but a request for some documentation on how to generate an APK from source code that can be run on appium-espresso-driver. 

I tried looking all over the issues log and documentation but there's no straight-forward way to do it. 

I am using Appium 1.19 on Java.

Any leads or guidance is highly appreciated. Thanks in advance.

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/appium/appium-espresso-driver#running ?

**Comment by kulasangeles** [comment]
Not really @KazuCocoa (appreciate the feedback)

I was following this guide https://appiumpro.com/editions/18-using-espresso-with-appium

The apk the guide provided here https://github.com/cloudgrey-io/the-app/releases/download/v1.5.0/TheApp-v1.5.0.apk is working on my local

My question is how do I produce an apk like the one above that will work with appium espresso driver. Meaning how do I build our Android app so it will work with espresso driver?

Sorry for being vague.

**Comment by KazuCocoa** [comment]
Np, I got it.

The app in the appiumpro looks like the app under test. When you/your developer build an apk to release/debug etc, then the apk is it.

So, if you already used an app on UIA2 driver before (with `app` capability), simply you can change the automationName to `espresso`.
Then, Appium handles the app for espresso driver.
https://appium.io/docs/en/drivers/android-espresso/

If you met something build errors like https://github.com/appium/appium-espresso-driver/issues/449, then you should tweak your app under test and espresso server's dependencies with https://github.com/appium/appium-espresso-driver#espresso-build-config since their dependencies are relevant to each other.

Build itself has done by Appium in the new session process, so you do not run build command separately.

**Comment by kulasangeles** [comment]
Hey @KazuCocoa I sorted it out thanks to your help. 

I documented our steps so I don't forget and had to introduce a couple of settings for the app build.gradle as well as the global build.gradle. 

For global build.gradle - is it possible for us to make the dependency repository configurable? (I can probably implement this though it will be my first time contributing) We are under a proxy and have our own dependency repo that's why I had to update it to point to our repo

for the app build.gradle - the build is complaining about the 64k limit for multidex so I had to add 'multiDexEnabled true' under defaultConfig

again thank you for your help and let me know how I can help back.

**Comment by KazuCocoa** [comment]
>  is it possible for us to make the dependency repository configurable? 

Yes. You can do it like https://github.com/appium/appium-espresso-driver#espresso-build-config does.

https://github.com/appium/appium-espresso-driver/blob/f7a0495facf2d41812e26cfd3cd36dc40a56a310/test/unit/server-builder-specs.js is the test code.

**Comment by kulasangeles** [comment]
Perfect! Working on it now! Thanks @KazuCocoa
