### ISSUE TITLE
Supported Devices Farm 

### ISSUE THREAD

**Issue by SaharBadran** [appium/appium-espresso-driver#676]
Hello All, 

Kindly need your help as I am able now to use Appium espresso local and it's working fine with me. Currently, I need to integrate the Appium espresso with the mobile farm to complete the CICD Cycle. Could you please tell me if you know a mobile farm that supports Appium Espresso [Able to launch Appium Espresso session using Mobile Farm ]

**Comment by KazuCocoa** [comment]
I think https://discuss.appium.io/ is more helpful to post such topic rather than here.
I'd like to suggest you to post this topic in the forum or ask cloud providers you're interested in.

Btw, I work in https://www.headspin.io/ . The platform supports espresso driver.

**Comment by Nadia-Adel** [comment]
Hi @KazuCocoa,
We tried to launch our app using appium espresso and headspin, but the session can't be launched and gives the below error:


A new session could not be created. Details: java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner} from pid=10191, uid=10191 not allowed because package io.appium.espressoserver.test does not have a signature matching the target com.vis.meinvodafone.dev at android.os.Parcel.createException(Parcel.java:2088) at android.os.Parcel.readException(Parcel.java:2056) at android.os.Parcel.readException(Parcel.java:2004) at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:6418) at com.android.commands.am.Instrument.run(Instrument.java:512) at com.android.commands.am.Am.runInstrument(Am.java:196) at com.android.commands.am.Am.onRun(Am.java:80) at com.android.internal.os.BaseCommand.run(BaseCommand.java:56) at com.android.commands.am.Am.main(Am.java:50) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:342) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:18896) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2818) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3426) at android.os.Binder.execTransactInternal(Binder.java:1056) at android.os.Binder.execTransact(Binder.java:1029)

Is there is any suggestion for solving that?

**Comment by KazuCocoa** [comment]
@Nadia-Adel Could you send a main via headspin support?
You can find the email address on your settings page.
(I guess signature stuff between your app under test and the espresso's sign)
