### ISSUE TITLE
how to debug driver in Android Studio

### ISSUE THREAD

**Issue by acton393** [appium/appium-espresso-driver#777]
**hi , I want to open a pull request to support "link text " strategy for finding element,  but it occurs some trouble to me.
 I  just run debug as bellow in Android studio, but  then it just** 
<img width="956" alt="image" src="https://user-images.githubusercontent.com/11631084/166880944-6c8ed967-1a56-4edd-964d-8a1a59e599a2.png">

**but then it just waiting at connecting debugger , I  just wonder whether it can be run in  debug mode.**

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/11631084/166881448-9221efb4-2603-4a44-ae84-4aec1df0c249.png">

**Comment by KazuCocoa** [comment]
I usually use "attach" to the running process after starting the espresso after starting espresso server via like ``adb shell am instrument io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner``

**Comment by acton393** [comment]
@KazuCocoa  Thanks for your  reply,

I have tried run from Android studio and then  try `attach ` to running process, but the  `espressoserver `  doesn't show in  running process  list. 

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/11631084/167164940-cf3d2b42-791f-4124-b7df-2bd263c67af8.png">


 I am sure  that `espressoserver`  has started as I can access status via http protocol in browser.

and also tried config `android:debuggable` follow the instruction [here](https://developer.android.com/studio/build/build-variants), but it doesn't work yet.

**Comment by KazuCocoa** [comment]
Espresso server itself does not appear since it is the app under test's process as Android.

For example, if the espresso server is built for `io.appium.android.apis`, you can attach to the package process.
<img width="467" alt="Screen Shot 2022-05-07 at 0 14 50" src="https://user-images.githubusercontent.com/5511591/167243395-d8595b72-b95f-4945-8acc-6ba0c3608d8f.png">

Then, you can set a breakpoint in the espresso's code. The below is in `source`.

<img width="1321" alt="Screen Shot 2022-05-07 at 0 11 32" src="https://user-images.githubusercontent.com/5511591/167243304-f2f6ddc0-078a-4675-a68c-a5595c91e9f4.png">

1. install `appium`
2. symlink `appium-espresso-server` package to this repository
3. Run an espresso session
4. Attach to the app under test's process

Probably these steps are probably an easier way to add a breakpoint
